// <auto-generated />
using System;
using APIMonitoramento.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIMonitoramento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIMonitoramento.Models.Medicoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("DataHoraMedicao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Medicao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("Id", "DataHoraMedicao")
                        .IsUnique();

                    b.ToTable("Medicoes");
                });

            modelBuilder.Entity("APIMonitoramento.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("SetorEquipamentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorEquipamentoId");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("APIMonitoramento.Models.SetorEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("SetorEquipamento");
                });

            modelBuilder.Entity("APIMonitoramento.Models.Medicoes", b =>
                {
                    b.HasOne("APIMonitoramento.Models.Sensor", null)
                        .WithMany("Medicoes")
                        .HasForeignKey("SensorId");
                });

            modelBuilder.Entity("APIMonitoramento.Models.Sensor", b =>
                {
                    b.HasOne("APIMonitoramento.Models.SetorEquipamento", "SetorEquipamento")
                        .WithMany("Sensores")
                        .HasForeignKey("SetorEquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetorEquipamento");
                });

            modelBuilder.Entity("APIMonitoramento.Models.Sensor", b =>
                {
                    b.Navigation("Medicoes");
                });

            modelBuilder.Entity("APIMonitoramento.Models.SetorEquipamento", b =>
                {
                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
